---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes

  - name: install unzip package
    yum:
      name: unzip

  - name: add php support for apache
    yum:
      name: libapache2-mod-php
